server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: kafka #tcp kafka rocketMQ rabbitMQ
  mqServers: localhost:9092
  zookeeperHosts: localhost:2181
  flatMessage: true
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://localhost:3306/es_sync?useUnicode=true
      username: canal
      password: Canal@123456

  consumer-properties:
    kafka.bootstrap.servers: localhost:9092
    kafka.enable.auto.commit: false
    kafka.auto.commit.interval.ms: 1000
    kafka.auto.offset.reset: latest
    kafka.request.timeout.ms: 40000
    kafka.session.timeout.ms: 30000
    kafka.isolation.level: read_committed
    kafka.max.poll.records: 1000

  canalAdapters:
    - instance: t_test_user_topic
      groups:
        - groupId: g1
          outerAdapters:
            - name: esCustom
              key: customETL
              hosts: http://localhost:9200
              properties:
                mode: transport
                security.auth: elastic:test
                cluster.name: dev

    - instance: t_test_role_topic
      groups:
        - groupId: g1
          outerAdapters:
            - name: esCustom
              hosts: http://localhost:9200
              properties:
                mode: transport
                security.auth: elastic:test
                cluster.name: dev

    - instance: t_test_user_role_topic
      groups:
        - groupId: g1
          outerAdapters:
            - name: esCustom
              hosts: http://localhost:9200
              properties:
                mode: transport
                security.auth: elastic:test
                cluster.name: dev

    - instance: t_test_tag_topic
      groups:
        - groupId: g1
          outerAdapters:
            - name: esCustom
              hosts: http://localhost:9200
              properties:
                mode: transport
                security.auth: elastic:test
                cluster.name: dev

    - instance: t_test_tag_topic
      groups:
        - groupId: g1
          outerAdapters:
            - name: esCustom
              hosts: http://localhost:9200
              properties:
                mode: transport
                security.auth: elastic:test
                cluster.name: dev

logging:
  level:
    com.alibaba.otter.canal.client.adapter.es.core.service.ESSyncService: trace
